In [5]:
import numpy as np
text = """NumPy, short for Numerical Python, is one of the most important foundational pack‐
ages for numerical computing in Python. Most computational packages providing
scientific functionality use NumPy’s array objects as the lingua franca for data
exchange.
Here are some of the things you’ll find in NumPy:
• ndarray, an efficient multidimensional array providing fast array-oriented arith‐
metic operations and flexible broadcasting capabilities.
• Mathematical functions for fast operations on entire arrays of data without hav‐
ing to write loops.
• Tools for reading/writing array data to disk and working with memory-mapped
files.
• Linear algebra, random number generation, and Fourier transform capabilities.
• A C API for connecting NumPy with libraries written in C, C++, or FORTRAN."""
nptext = np.array(text.split())
print(type(nptext))
print(nptext[:10], "\n", len(nptext))

<class 'numpy.ndarray'>
['NumPy,' 'short' 'for' 'Numerical' 'Python,' 'is' 'one' 'of' 'the' 'most'] 
 117


In [50]:
arr = np.arange(10)

arr = np.arange(5,10)
arr = np.array([-1, -2, 1 ,2, 4, -8], dtype="float")
#print(arr[:10])
x = arr.shape
#print(np.abs(arr) 
#rint(arr.shape, arr.dtype, arr.ndim)
d3 = np.array([ [
                  [111, 112, 113] , 
                  [121, 122, 123] 
                ],
                [ 
                  [211, 212, 213] , 
                  [221, 222, 224] 
                ],
                [
                  [311, 312, 313], 
                  [321, 322, 323]
                ],
                [
                  [411, 412, 413],
                  [421, 422, 423] 
                ]
              ])
            
             
print("array", d3)
print("size", d3.size)
print("shape", d3.shape)
print("dimensions", d3.ndim)
x = list(d3)
print(x
print(type(x))


array [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 224]]

 [[311 312 313]
  [321 322 323]]

 [[411 412 413]
  [421 422 423]]]
size 24
shape (4, 2, 3)
dimensions 3
[array([[111, 112, 113],
       [121, 122, 123]]), array([[211, 212, 213],
       [221, 222, 224]]), array([[311, 312, 313],
       [321, 322, 323]]), array([[411, 412, 413],
       [421, 422, 423]])]
<class 'list'>


In [55]:
# vectorization
arr = np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(arr * 6) # scaler operation will propagte
print(arr[:3] * 6)
# in list we can not do that
#x =list(arr)
#print(x * 6)


[  72 -270  402  534  204  -12  -12   36  -42   48]
[  72 -270  402]


In [64]:
# equal array operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[4,11,6]])

c = a + b
print(c)

# broadcasting (row size should be same)
d = np.array([4,3,2])
print("d array", d)
print(c.shape, d.shape)
print(c + d)


[[ 8 10 12]
 [ 8 16 12]]
d array [4 3 2]
(2, 3) (3,)
[[12 13 14]
 [12 19 14]]
[[False False False]
 [ True False  True]]


In [88]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[4,11,6]])

# comparing array will return boolean array
# we can use boolean array for filtering data
boolean_e = (a == b)
c = a + b
x = 15
boolean_e = c < 15
print(boolean_e)
# filtering data using boolean array
cFilter  = c[boolean_e]
# direct filter instead of boolean array
cFilter  = c[c < 15]

print(cFilter)

[[ True  True  True]
 [ True False  True]]
[ 8 10 12  8 12]


In [93]:
age = 10
x = age < 10
print(age < 10)


False


In [115]:
# indexing and fancy indexing
arr = np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(arr[4]) # indexing
# fancy indexing
ind = [1, 4, 6]
print(arr[ ind ])
print(arr [[1, 4, 6] ])
# slicing
print(arr [2:5 ])
# slicing in two diminesion
print("\n\nslicing")
a = np.array([[1,2,3],[4,5,6], [41,51,61], [42,52,62]])
print(a[1:3, 2:3, ])

34
[-45  34  -2]
[-45  34  -2]
[67 89 34]


slicing
[[ 6]
 [61]]


In [111]:
# element wise operation
arr = np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(np.abs(arr))


[12 45 67 89 34  2  2  6  7  8]
