In [10]:
import numpy as np
import matplotlib.pylab as plt
def plti(im, h=8, **kwargs):
    """
    Helper function to plot an image.
    """
    y = im.shape[0]
    x = im.shape[1]
    w = (y/x) * h
    plt.figure(figsize=(w,h))
    plt.imshow(im, interpolation="none", **kwargs)
    plt.axis('off')
    #input('press <ENTER> to continue')
%matplotlib inline
im = plt.imread("airplane.png")
print(type(im ) )
#plti(im)
#im = im[400:3800,:2000,:]    
#plti(im)
#print( im.shape )
print(im[:5, :10, :10])

#im = im[400:3800,:2000,:]    
#plti(im)

<class 'numpy.ndarray'>
[[[0.70980394 0.         0.38431373]
  [0.7254902  0.80784315 0.7921569 ]
  [0.64705884 0.8117647  0.77254903]
  [0.5019608  0.827451   0.8       ]
  [0.42745098 0.827451   0.7921569 ]
  [0.56078434 0.79607844 0.78431374]
  [0.6392157  0.8        0.7764706 ]
  [0.62352943 0.79607844 0.7607843 ]
  [0.627451   0.8039216  0.76862746]
  [0.6431373  0.80784315 0.78431374]]

 [[0.5529412  0.         0.42352942]
  [0.78039217 0.75686276 0.8       ]
  [0.7647059  0.7411765  0.78431374]
  [0.7647059  0.75686276 0.8117647 ]
  [0.7607843  0.75686276 0.8       ]
  [0.7529412  0.74509805 0.78431374]
  [0.7490196  0.7411765  0.79607844]
  [0.75686276 0.74509805 0.78431374]
  [0.7529412  0.72156864 0.7647059 ]
  [0.75686276 0.7529412  0.7921569 ]]

 [[0.5529412  0.         0.42352942]
  [0.77254903 0.76862746 0.79607844]
  [0.75686276 0.75686276 0.78039217]
  [0.7607843  0.76862746 0.8117647 ]
  [0.7647059  0.7607843  0.78431374]
  [0.73333335 0.7490196  0.79607844]
  [0.73725